"$schema" = 'https://starship.rs/config-schema.json'
# Pipes â•°â”€ â•­â”€
# Powerline symbols Â î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿ îƒ€ îƒ îƒ‚ îƒƒ îƒ„ îƒ… îƒ† îƒ‡ îƒˆ îƒŠ  îƒŒ îƒ îƒ îƒ îƒ îƒ‘ îƒ” îƒ’ 
# Wedges ğŸ­§ğŸ­’ ğŸ­£ğŸ­§ğŸ­“
# Random noise ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—
# Cool stuff ó°œ¥ î©± ï‹ ï€

add_newline = true
command_timeout = 8000
scan_timeout = 6000

#fomart = """
#[îƒ‡ ](fg:bg_2)\
#[ ](bg:bg_1)\
#$os\
#$directory\
#$git_branch\
#$git_status\
#[îƒ† ](fg:bg_2)\
#$line_break\
#[îƒ‡ ](fg:bg_2)\
#[ ](bg:bg_1)\
#$character\
#$shell\
#[î‚° ](fg:bg_1)
#"""


format = """
[îƒ‡ ](fg:bg_2)\
[ ](bg:bg_1)\
$directory\
$shell\
[î‚°](fg:bg_1 bg:bg_2)\
[î‚° ](fg:bg_2)
"""

right_format = """
[îƒ‡ ](fg:bg_2)\
[ ](bg:bg_1)\
$os\
[ ](bg:bg_1)\
$character\
$git_branch\
$git_status\
[îƒ† ](fg:bg_2)
"""

palette = "matugen"
#palette = "backshot"

[shell]
disabled = false
bash_indicator = 'î¯Š '
fish_indicator = 'ó°ˆº '             #ğŸŸ
zsh_indicator = "ó°°¶ "
powershell_indicator = 'î¯‡ '       # ï‘ 
cmd_indicator = 'î¯„ '              #î˜©
ion_indicator = 'î™« '
elvish_indicator = "ó°˜§"
tcsh_indicator = "ó°°¤ "
nu_indicator = "nu"
xonsh_indicator = "ğŸš"             # seashell emoji
unknown_indicator = 'îš‘ '
style = "bold fg:fg_1 bg:bg_1"
format = "[ $indicator ]($style)" #space on right b/c double-width symbol

[git_branch]
symbol = "ï˜ "
style = "bold fg:fg_1 bg:bg_1"
format = '[[ $symbol $branch ](fg:fg_1 bg:bg_1)]($style)'

[git_status]
style = "fg:fg_1 bg:bg_1"
format = '[[($all_status$ahead_behind )](fg:fg_1 bg:bg_1)]($style)'

[directory]
disabled = false
style = "bold fg:fg_2 bg:bg_1"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "ï““ ó°®º "

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "
"Templates" = "ï”… "
"Steam" = "ï†¶ "
"Github" = "ï‚› "
".config" = "î˜• "

[palettes.matugen]
bg_0 = "#1c1016"
fg_0 = "#f4dde5"
# Text
fg_4 = "#93000a"
fg_3 = "#532025"
fg_2 = "#620043"
fg_1 = "#3c0028"
fg_o = "#8a0061"
# Background
bg_2 = "#8a0061"
bg_1 = "#ffafd7"


[palettes.backshot]
bg_0 = "#000000"
fg_0 = "#000000"
fg_o = "#CAF0F8"
bg_1 = "#0D41E1"
fg_1 = "#ffffff"
bg_2 = "#0C63E7"
fg_2 = "#E85C90"

fg_3 = "#109648"
fg_4 = "#980123"

[line_break]
disabled = true

[os]
format = "[$symbol]($style)"
style = "bold fg:fg_o bg:bg_1"
disabled = false

[os.symbols]

AIX = "â¿ "
Alpaquita = "îª¢ "   #alpaca
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "     #îœ
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "î»¸ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
#GhostBSD = "ó°Š  "
HardenedBSD = "ó°Œ "
Illumos = "ïŒ¦ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "             #ğŸŒ¿
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ïŒ¨ "          #ó°ˆº
OpenCloudOS = 'î®ª'
openEuler = 'ï…¼'
openSUSE = "ïŒ” "
OracleLinux = "î¡™ "      #ó°Œ· âŠ‚âŠƒ
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ó°€˜ "
RockyLinux = "ïŒ« "
Solus = "ó° ³ "            #ïŒ­
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Ultramarine = "ó°¼® "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "î˜ª "          #îœ


[character]
success_symbol = "[ï€„ ](fg:fg_2 bg:bg_1)" #âœ…
error_symbol = "[î½¶ ](fg:fg_4 bg:bg_1)"   #â›”
format = "[$symbol](bg:bg_1)"
# No runtime need

[bun]
format = "via [$symbol]($style)"

[buf]
format = "with [$symbol]($style)"

[c]
format = "via [$symbol($name)]($style)"

[cmake]
format = "via [$symbol]($style)"

[cobol]
format = "via [$symbol]($style)"

[cpp]
format = "via [$symbol($name)]($style)"

[crystal]
format = "via [$symbol]($style)"

[daml]
format = "via [$symbol]($style)"

[dart]
format = "via [$symbol]($style)"

[deno]
format = "via [$symbol]($style)"

[dotnet]
format = "[$symbol(ğŸ¯ $tfm )]($style)"

[elixir]
format = 'via [$symbol]($style)'

[elm]
format = 'via [$symbol]($style)'

[erlang]
format = 'via [$symbol]($style)'

[fennel]
format = 'via [$symbol]($style)'

[fortran]
format = 'via [$symbol]($style)'

[gleam]
format = 'via [$symbol]($style)'

[golang]
format = 'via [$symbol]($style)'

[gradle]
format = 'via [$symbol]($style)'

[haskell]
format = 'via [$symbol]($style)'

[haxe]
format = 'via [$symbol]($style)'

[helm]
format = 'via [$symbol]($style)'

[java]
format = 'via [$symbol]($style)'

[julia]
format = 'via [$symbol]($style)'

[kotlin]
format = 'via [$symbol]($style)'

[lua]
format = 'via [$symbol]($style)'

[meson]
format = 'via [$symbol]($style)'

[mojo]
format = 'with [$symbol]($style)'

[nim]
format = 'via [$symbol]($style)'

[nodejs]
format = 'via [$symbol]($style)'

[ocaml]
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'

[odin]
format = 'via [$symbol]($style)'

[opa]
format = 'via [$symbol]($style)'

[perl]
format = 'via [$symbol]($style)'

[php]
format = 'via [$symbol]($style)'

[pixi]
format = 'via [$symbol($environment )]($style)'

[pulumi]
format = 'via [$symbol$stack]($style)'

[purescript]
format = 'via [$symbol]($style)'

[python]
format = 'via [$symbol]($style)'

[quarto]
format = 'via [$symbol]($style)'

[raku]
format = 'via [$symbol]($style)'

[red]
format = 'via [$symbol]($style)'

[rlang]
format = 'via [$symbol]($style)'

[ruby]
format = 'via [$symbol]($style)'

[rust]
format = 'via [$symbol]($style)'

[scala]
format = 'via [$symbol]($style)'

[solidity]
format = 'via [$symbol]($style)'

[swift]
format = 'via [$symbol]($style)'

[typst]
format = 'via [$symbol]($style)'

[vagrant]
format = 'via [$symbol]($style)'

[vlang]
format = 'via [$symbol]($style)'

[xmake]
format = "via [$symbol]($style)"

[zig]
format = 'via [$symbol]($style)'
